version: '3'

services:
  tire-diagnostic:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
